apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fruitjokes
  annotations:
    version: v0.0.1
    description: "WasmCon fruit jokes"
spec:
  components:
    - name: fruitjokes
      type: actor
      properties:
        image: registry.cosmonic.sh/374b6434-f18d-4b93-8743-bcd3089e4d5b/fruitjokes:0.1.0
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: keyvalue
        - type: linkdef
          properties:
            target: httpserver

    - name: httpserver
      type: capability
      properties:
        image: cosmonic.azurecr.io/httpserver_wormhole:0.6.0
        contract: wasmcloud:httpserver
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
    - name: keyvalue
      type: capability
      properties:
        image: cosmonic.azurecr.io/builtin_keyvalue:0.2.4
        contract: wasmcloud:keyvalue
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
