name = "BranchManager"
language = "rust"
type = "actor"

[actor]
wasm_target = "wasm32-wasi-preview1"
claims = [
    "wasmcloud:messaging",
    "wasmcloud:builtin:logging",
    "wasmcloud:keyvalue",
    "wasmcloud:httpserver",
]
