apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: munder-difflin
  annotations:
    version: v0.1.0-local
    description: "Industry leading paper company"
spec:
  components:
    - name: branchmanager
      type: actor
      properties:
        image: file:///Users/brooks/github.com/brooksmtownsend/wasmcon-backend-cdn/industry/branchmanager/build/branchmanager_s.wasm
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
            spread:
              - name: branch
                requirements:
                  branch: "true"
        - type: linkdef
          properties:
            target: messaging
            values:
              SUBSCRIPTION: munderdifflin.>
        - type: linkdef
          properties:
            target: keyvalue
        - type: linkdef
          properties:
            target: httpserver_local
            values:
              address: 0.0.0.0:8080
    - name: corporatedashboard
      type: actor
      properties:
        image: file:///Users/brooks/github.com/brooksmtownsend/wasmcon-backend-cdn/industry/corporatedashboard/build/corporatedashboard_s.wasm
      traits:
        - type: daemonscaler
          properties:
            replicas: 3
            spread:
              - name: branch
                requirements:
                  branch: "true"
        - type: linkdef
          properties:
            target: messaging
            values:
              SUBSCRIPTION: corporate.>
        - type: linkdef
          properties:
            target: keyvalue
        - type: linkdef
          properties:
            target: httpserver_local
            values:
              address: 0.0.0.0:8081

    - name: messaging
      type: capability
      properties:
        image: wasmcloud.azurecr.io/nats_messaging:0.17.4
        contract: wasmcloud:messaging
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
    - name: httpserver_local
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.19.1
        contract: wasmcloud:httpserver
        link_name: local
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
            spread:
              - name: branch
                requirements:
                  branch: "true"
    - name: keyvalue
      type: capability
      properties:
        image: wasmcloud.azurecr.io/kvredis:0.22.0
        contract: wasmcloud:keyvalue
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
            spread:
              - name: branch
                requirements:
                  branch: "true"
