apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: industry-inventory
  annotations:
    version: v0.3.0
    description: "Industry inventory management system"
spec:
  components:
    - name: unitmanager
      type: actor
      properties:
        image: registry.cosmonic.sh/374b6434-f18d-4b93-8743-bcd3089e4d5b/unitmanager:0.3.0
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
            spread:
              - name: unit
                requirements:
                  unit: "true"
        - type: linkdef
          properties:
            target: messaging
            values:
              SUBSCRIPTION: unit.>
              URI: nats://0.0.0.0:4223
        - type: linkdef
          properties:
            target: keyvalue
        - type: linkdef
          properties:
            target: httpserver_local
            values:
              address: 0.0.0.0:8080
    - name: hubdashboard
      type: actor
      properties:
        image: registry.cosmonic.sh/374b6434-f18d-4b93-8743-bcd3089e4d5b/hubdashboard:0.3.0
      traits:
        - type: daemonscaler
          properties:
            replicas: 3
            spread:
              - name: hub
                requirements:
                  cosmonic_managed: "true"
        - type: linkdef
          properties:
            target: messaging
            values:
              SUBSCRIPTION: hub.>
        - type: linkdef
          properties:
            target: builtinkv
        - type: linkdef
          properties:
            target: httpserver

    - name: httpserver
      type: capability
      properties:
        image: cosmonic.azurecr.io/httpserver_wormhole:0.6.2
        contract: wasmcloud:httpserver
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
    - name: builtinkv
      type: capability
      properties:
        image: cosmonic.azurecr.io/builtin_keyvalue:0.2.5
        contract: wasmcloud:keyvalue
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: "true"
          type: spreadscaler
    - name: messaging
      type: capability
      properties:
        image: wasmcloud.azurecr.io/nats_messaging:0.17.4
        contract: wasmcloud:messaging
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
    - name: httpserver_local
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.19.1
        contract: wasmcloud:httpserver
        link_name: local
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
            spread:
              - name: unit
                requirements:
                  unit: "true"
    - name: keyvalue
      type: capability
      properties:
        image: wasmcloud.azurecr.io/kvredis:0.22.0
        contract: wasmcloud:keyvalue
      traits:
        - type: daemonscaler
          properties:
            replicas: 1
            spread:
              - name: unit
                requirements:
                  unit: "true"
